### ISSUE TITLE
kube-inject support for debug images

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#13]
@andraxylia commented on [Thu May 04 2017](https://github.com/istio/pilot/issues/666)

Add a flag --debug for kube-inject so the resulting injected proxy and init use the debug baseline image.

---

@andraxylia commented on [Tue May 09 2017](https://github.com/istio/pilot/issues/666#issuecomment-300368492)

Partialy fixed in istio/manager#702 for alpha, moving to beta to add the flag.

**Comment by mandarjog** [comment]
@ayj this is part of initializer sidecar injection. Can we inject debug images thru it?

**Comment by ayj** [comment]
In theory yes, but it isn't supported in the initial implementation.
