### ISSUE TITLE
Design for basic end-user authentication

### ISSUE THREAD

**Issue by ayj** [istio/galley#15]
Configuration component should initially support basic end-user auth (self-signed cert, oauth?). This can be added incrementally so long as all access to the storage layer is via proper REST/gRPC API. 
 
RBAC requirements and design should be considered later.

**Comment by ldemailly** [comment]
we should auth also pilot-galley and mixs-galley traffic. and if there is going to be a way (like today's mixer) to push config to components they shouldn't accept that push unless it carries the galley credential

**Comment by ayj** [comment]
cc @istio/auth-hackers

**Comment by myidpt** [comment]
For for the simplicity, we may want to start the end user auth with JWT/mTLS. Galley should use a certificate to authenticate itself to pilot and mixer, so the channel is mTLS just like service-to-service auth.

**Comment by lizan** [comment]
Securing pilot-galley and mixs-galley traffic should be tracked in another issue. For end user auth, HTTPS + JWT (OAuth) should be fine. @mtakigiku will work with me on this.

**Comment by lizan** [comment]
0.3 or later, this originally required by galley for 0.2, but the requirement no longer exists.

**Comment by mandarjog** [comment]
We use k8s api server auth. No work to be done here.
