### ISSUE TITLE
Design for safely manipulating secrets

### ISSUE THREAD

**Issue by ayj** [istio/galley#18]
Galley needs a solution to allow producers and consumers of Istio configuration to manipulate references to secrets. The secrets themselves should not be stored in Galley.

**Comment by ayj** [comment]
@istio/auth-hackers, @wenchenglu

**Comment by ldemailly** [comment]
> The secrets themselves should not be stored in Galley.

where then / why not?

shouldn't they just be protected ?

**Comment by myidpt** [comment]
Are they K8s secrets? Can you be more specific about manipulating the references to secrets? Does it grant producers/consumers permissions to access the secrets or something else?

**Comment by ayj** [comment]
From [Proposal: Galley (Istio Configuration)](https://docs.google.com/document/d/13UqmYpEjNGT2xucIgWaTQIQUgQuAASeIdm8Ks3zp5Fk/edit#bookmark=id.s027slt4cgqr):

> The Istio configuration model may include secrets which need to be stored in a secured vault and not the configuration storage. The configuration component should support the notion of secrets as a first class thing and provide necessary APIs to enable producers and consumers of Istio configuration to handle references to secrets.

In particular, its desirable to avoid re-inventing a secret store and instead use an existing system, e.g. https://www.vaultproject.io, k8s secrets. Istio configuration resources would reference secrets in these stores without storing the secrets themselves in Galley. For example, 

- Mixer needs secure credentials to program backend infrastructure. 
- Operator (producer) creates Istio configuration along with reference to secure credentials.
- Mixer (consumer) uses the secret reference to get the actual secret via the secret store. Mixer can then program the backend infrastructure with corresponding configuration. 

Galley would not be responsible for managing permissions on secrets.

**Comment by ldemailly** [comment]
There is a bootstrap issue there and I don't think we can avoid managing secret as that's core to the functionality of Istio - but happy to be shown we don't.

also if we have a seperate secret store (is it in auth?) we need an implementation for rawvm and hybrid

**Comment by wenchenglu** [comment]
There are different types of secrets we need to manage:
(1) key/cert for establishing mTLS for service-to-service auth
(2) credentials (api key, jwt, auth token, username/password, etc.) to access backends or remote services

Is this issue mostly about the case (2)? I agree that Vault is a good option considering its popularity as a secret store. For case (1), Vault is optional since key/cert can be stored in local memory of each node. We can still use Vault + PKI backend as CA, which is not mainly for storage in this case though.

**Comment by myidpt** [comment]
So if the configuration is just a reference, Galley is not able to verify if the producer really has permission to access the secret, right? After the operator writes the secret in Vault, how does the operator grant permission to Mixer/service to access the secret?

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by wenchenglu** [comment]
not 0.2

**Comment by kyessenov** [comment]
Issue moved to [istio/api #161](https://github.com/istio/api/issues/161) via [**ZenHub**](https://www.zenhub.com/)
