### ISSUE TITLE
Server-side config validation via adapter

### ISSUE THREAD

**Issue by ayj** [istio/galley#19]
Design and implement server-side cofign validation for the following:

* basic syntactic
* basic semantic
* validation over time (ex quota 50% over time causes outages or operational problems). 

Validation may be implemented as runtime admission controller extension (a. la k8s) to avoid tight coupling of Galley with Mixer and Pilot. Registration will be restricted to only at initialization. Galley will not be in the runtime request path so it will be ok to restart it for a new adapter.

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by mandarjog** [comment]
This is 0.2.

**Comment by kyessenov** [comment]
there're issues for CRD validation in each repo (pilot and mixer)
