### ISSUE TITLE
move istioctl and contrib/cfgeditor from pilot to galley

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#2]

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ayj** [comment]
This would be nice to have but not necessary for 0.2 release. Mixer team plans to use kubectl directly from configuration which removes istio/mixer dependency on istio/pilot. Istioctl is only necessary for kube-inject which shares logic with sidecar initializer and that resides in istio/pilot for the time being. We can spilt istioctl/initializer into their own repo once that other majors changes settle down.

**Comment by ayj** [comment]
cc @mandarjog @kyessenov
