### ISSUE TITLE
Implement etcd storage adapter

### ISSUE THREAD

**Issue by ayj** [istio/galley#20]
Use etcd as the reference implementation for the Istio configuration storage backend. 

Most of the design and implementation has already been done in the context of istio/pilot (see https://github.com/istio/pilot/issues/850 and https://github.com/istio/pilot/pull/870). We could let the adapter design/implementation continue in istio/pilot or move it into istio/galley with the understanding that it would eventually be moved into istio/galley.

ref https://docs.google.com/document/d/13UqmYpEjNGT2xucIgWaTQIQUgQuAASeIdm8Ks3zp5Fk/edit#bookmark=id.l5ok08mvkqux

**Comment by jmuk** [comment]
finished by #38
