### ISSUE TITLE
Galley client: works without requiring HA config server - local snapshot, disconnected mode

### ISSUE THREAD

**Issue by ldemailly** [istio/galley#23]
Galley client: works without requiring HA config server - local snapshot, disconnected mode

availability of config servers, or network partition doesn’t mean proxy / service being unavailable and we don't need an HA storage solution available in each pod to achieve that

**Comment by kyessenov** [comment]
What is the situation that config is unreachable but proxy is reachable?

How do we deal with inconsistent states of proxies on the endpoints of the wire, e.g. if one proxy is behind other one in config state? for TCP and HTTP?

**Comment by ldemailly** [comment]
> What is the situation that config is unreachable but proxy is reachable?
the vm crashed, a bad config binary has been deployed, a rack switch is dead,... 100s of scenarios

>How do we deal with inconsistent states of proxies on the endpoints of the wire, e.g. if one proxy is behind other one in config state? for TCP and HTTP?

- the same way we deal with the fact nothing propagates instantaneously anyway
- with alerting when local config is abnormally stale

**Comment by kyessenov** [comment]
1. I was looking for reasons we would want a proxy in the mesh if its config is broken.

2. "Stale" is a matter of fact as we learned today. We don't have globally consistent atomic clocks in our docker instances :)

**Comment by ldemailly** [comment]
> I was looking for reasons we would want a proxy in the mesh if its config is broken.

because it should continue running with the last good config instead of creating an outage

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ldemailly** [comment]
moved to 0.3

**Comment by mandarjog** [comment]
Galley client is k8s client-go cache. No work needs to be done here.
