### ISSUE TITLE
istioctl CLI version subcommand should include information about the control plane version

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#3]
@esnible commented on [Fri Mar 10 2017](https://github.com/istio/pilot/issues/293)

It is difficult for users to know if their third party resource exists and if their Istio control plane is running.

`istioctl version` should work like `kubectl version` and return similar information about the version of the Istio components running on the cluster manager.

---

@esnible commented on [Fri Mar 10 2017](https://github.com/istio/pilot/issues/293#issuecomment-285746188)

See #169 for the version of the CLI appearing as a subcommand.

---

@esnible commented on [Fri Mar 10 2017](https://github.com/istio/pilot/issues/293#issuecomment-285788254)

_istioctl_ doesn't have direct access to the control plane.  Currently the IstioConfig does not know what version of Istio is running.

Once #251 is implemented it will be possible, in the Kubernetes environment, to get the REST address of the discovery and mixer services from IstioConfig/MeshConfig and ask them what versions they are.  Alternately when they start they could tell IstioConfig their version as well as their address.

Once #227 is implemented the manager will have a REST layer that can be queried in the same way.

This Issue should be considered blocked until progress is made on those issues.

---

@esnible commented on [Thu May 18 2017](https://github.com/istio/pilot/issues/293#issuecomment-302404783)

@liamawhite May I take this one over?  I am doing the server side as well.

**Comment by esnible** [comment]
We should close this; `istioctl version` now shows both apiserver and istioctl version.

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ayj** [comment]
We no longer have our own dedicated API server. User's should be able to query the version of individual Istio components, e.g. 

At a minimum we should support the following:
```bash
kubectl proxy &
curl localhost:8001/api/v1/namespaces/istio-system/services/istio-pilot:8080/proxy/version
curl localhost:8001/api/v1/namespaces/istio-system/services/istio-mixer:9091/proxy/version
```

Istioctl could provide a wrapper around this.

**Comment by ldemailly** [comment]
There is another issue about incomplete version dump by istioctl (on phone so hard to search, it's in pilot or istio)

**Comment by ldemailly** [comment]
closing in favor of https://github.com/istio/istio/issues/358
