### ISSUE TITLE
Define storage abstraction layer API

### ISSUE THREAD

**Issue by andraxylia** [istio/galley#30]
This involves defining the package-level API for the key/value store abstraction layer that Galley depends on.

**Comment by jmuk** [comment]
It's actually within my PR https://github.com/istio/galley/pull/28 already (it's based on the `KeyValueStore` in mixer currently). I can extract the store code first if needed.

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ayj** [comment]
No longer relevant with [k8s apiserver alignment.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-core/P1io6xBaxaA/QTdd_oSYBgAJ )
