### ISSUE TITLE
Securing cross component configuration traffic

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#5]
@ayj commented on [Wed Jun 07 2017](https://github.com/istio/pilot/issues/840)

Istio API/Configuration server does not have support for auth. Any pod/service with network access can create/modify/delete rules. Ideally we might want to support RBAC but initially it would be good to have basic cert/oauth support.

---

@kyessenov commented on [Wed Jun 07 2017](https://github.com/istio/pilot/issues/840#issuecomment-306957893)

@lookuptable do we have a design for control plane auth and bootstrapping control plane identities?

---

@ldemailly commented on [Thu Jun 08 2017](https://github.com/istio/pilot/issues/840#issuecomment-307144017)

Not just pilot but mixer too

**Comment by ayj** [comment]
Tracked by https://github.com/istio/galley/issues/15

**Comment by ldemailly** [comment]
> Securing pilot-galley and mixs-galley traffic should be tracked in another issue.

**Comment by ayj** [comment]
k8s apiserver support RBAC.

**Comment by rshriram** [comment]
closing in favor of move to api server
