### ISSUE TITLE
Drop the file's metadata?

### ISSUE THREAD

**Issue by jmuk** [istio/galley#55]
It makes me wonder what is the role of metadata in `File` message. Who is going to use that for which purpose, considering the user can bring the metadata into the `ConfigFile` already. Maybe we don't need to have extra metadata outside of the user content, right?

**Comment by ayj** [comment]
No longer relevant with [k8s apiserver alignment.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-core/P1io6xBaxaA/QTdd_oSYBgAJ )
