### ISSUE TITLE
clarify the contents for "PROTO_TEXT" content type

### ISSUE THREAD

**Issue by jmuk** [istio/galley#60]
The galley API currently have `PROTO_TEXT` content type (https://github.com/istio/galley/blob/master/api/galley/v1/service.proto#L92), but no one specifies how it will look like.

I was thinking it as the ascii format of a ConfigFile message. Eitherway, it needs to specify much more.

**Comment by ayj** [comment]
No longer relevant with [k8s apiserver alignment.](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/istio-core/P1io6xBaxaA/QTdd_oSYBgAJ )
