### ISSUE TITLE
istioctl --kube ... still attempts to read ~/.kube/config

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#7]
@esnible commented on [Thu May 25 2017](https://github.com/istio/pilot/issues/814)

To reproduce:

```
$ rm ~/.kube/config
$ istioctl version --kube=false get route-rules
Error: failed to connect to Kubernetes API. kubernetes configuration file "/home/vagrant/.kube/config" does not exist
```

**Comment by sakshigoel12** [comment]
Please update milestone and assignee

**Comment by ayj** [comment]
cc @kyessenov @mandarjog 

This should be no longer relevant with k8s apiserver alignment. Pilot already uses CRD directly and Mixer will shortly. At this point istioctl will be only required for kube-inject and non-k8s storage (not-supported?)

**Comment by ldemailly** [comment]
Did you verify it doesn't error out anymore?
