### ISSUE TITLE
Add version checks to API/Config server

### ISSUE THREAD

**Issue by kyessenov** [istio/galley#9]
@ayj commented on [Wed May 10 2017](https://github.com/istio/pilot/issues/715)

Istio Config server (manager/mixer) should have version check for backwards incompatibility with older versions of pre-alpha/alpha istioctl. Longer term (beta/post-beta) the API and config server should maintain backwards compatibility and/or fail gracefully.

---

@ayj commented on [Thu May 11 2017](https://github.com/istio/pilot/issues/715#issuecomment-300863089)

From https://github.com/istio/manager/issues/722

> hackathon feedback:
> 
> gcloud (and other command line tools) check if a newer version is available. This would be very useful from a user experience standpoint.

> More importantly, istioctl should negotiate a version with the remote in-cluster apiserver.

**Comment by sakshigoel12** [comment]
Is this for 0.2 or 0.3?

**Comment by ayj** [comment]
This is no longer relevant now that we're using k8s apiserver for configuration.
